-- ============================================================
-- 查验证明：19 条店铺数据（图片已上传 licenses 桶）
-- 在 Supabase SQL Editor 执行（licenses 表建好后）
-- 注意：请勿重复执行本 SQL（会插入重复数据）
-- ============================================================
insert into public.licenses (platform, shop_name, shop_short, company, factory, license_file, business_file, production_file, sort_order) values
('抖音', '弥生官方旗舰店', '抖音1店', '铜陵洛吟电子商务有限公司', '吉林瑞尔康', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/jilin-ruierkang/production.webp', 1),
('抖音', '弥生美瞳旗舰店', '抖音2店', '铜陵洛吟电子商务有限公司', '西安科诗美', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/xian-keshimei/production.webp', 2),
('抖音', '弥生眼镜旗舰店', '抖音3店', '铜陵洛吟电子商务有限公司', '陕西福蔻', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/shaanxi-fukou/production.webp', 3),
('抖音', '弥生电子美瞳专卖店', '抖音4店', '铜陵洛吟电子商务有限公司', '江苏天眼', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/jiangsu-tianyan/production.webp', 4),
('快手', '快手-弥生旗舰店', '快手弥生', '铜陵洛吟电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', '', 5),
('拼多多', '弥生美瞳旗舰店', '拼多多1店', '铜陵洛吟电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', '', 6),
('拼多多', '弥生美瞳官方旗舰店', '拼多多2店', '杭州涉吉电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-sheji/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-sheji/business.webp', '', 7),
('拼多多', '弥生官方旗舰店', '拼多多3店', '杭州涉吉电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-sheji/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-sheji/business.webp', '', 8),
('拼多多', '弥生隐形眼镜官方旗舰店', '拼多多4店', '铜陵洛吟电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', '', 9),
('拼多多', '弥生MIUSOU官方旗舰店', '拼多多5店', '杭州沐曦电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-muxi/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-muxi/business.webp', '', 10),
('拼多多', '弥生隐形眼镜旗舰店', '拼多多7店', '等新公司下证', '', '', '', '', 11),
('拼多多', 'YOUHOO美瞳旗舰店', '拼多多YH', '杭州呦吼贸易有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-youhou/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-youhou/business.webp', '', 12),
('天猫', '弥生旗舰店', '天猫弥生', '铜陵洛吟电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', '', 13),
('天猫', '极氧旗舰店', '天猫极氧', '杭州松沛电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-songpei/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-songpei/business.webp', '', 14),
('抖音', 'YOUHOO美瞳旗舰店', '抖音YH', '杭州呦吼贸易有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-youhou/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-youhou/business.webp', '', 15),
('抖音', '极氧美瞳旗舰店', '抖音极氧', '杭州泷吟电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-longyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-longyin/business.webp', '', 16),
('小红书', '弥生旗舰店', '小红书弥生', '杭州尤赫电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-youhe/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-youhe/business.webp', '', 17),
('小红书', '极氧旗舰店', '小红书极氧', '杭州呦吼贸易有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-youhou/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/hangzhou-youhou/business.webp', '', 18),
('京东', '弥生旗舰店', '京东弥生', '铜陵洛吟电子商务有限公司', '', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/license.webp', 'https://ienmejlxukhrxjjxvfqf.supabase.co/storage/v1/object/public/licenses/tongling-luoyin/business.webp', '', 19)
on conflict (id) do nothing;

-- 完成提示
select '19 条店铺数据已上架' as result;