-- ============================================================
-- 修复：qc_records.id 缺失自增，导致新增记录报错
--   null value in column "id" of relation "qc_records"
--   violates not-null constraint
-- 原因：线上表是旧脚本建的（id BIGINT PRIMARY KEY，无默认值），
--       前端插入省略 id 时数据库不会自动生成。
-- 用法：Supabase SQL Editor 整段执行，可重复运行（幂等）。
-- ============================================================

-- 0) 先看一眼当前定义（执行完可再跑一次对比）
SELECT table_name, column_name, is_identity, identity_generation, column_default
FROM information_schema.columns
WHERE table_name = 'qc_records' AND column_name = 'id';

-- 1) 如果 id 没有 identity 自增属性，就补上（已有时自动跳过）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'qc_records'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE qc_records
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    RAISE NOTICE '已为 qc_records.id 补上自增 identity';
  ELSE
    RAISE NOTICE 'qc_records.id 已有自增，跳过';
  END IF;
END $$;

-- 2) 把序列拨到现有最大 id 之后（表里有历史数据时防止主键冲突）
SELECT setval(
  pg_get_serial_sequence('qc_records', 'id'),
  COALESCE((SELECT MAX(id) FROM qc_records), 0) + 1,
  false
);

-- 3) 顺手体检：其它 qc_* 表的 id 是否也有同样隐患
--    is_identity = NO 且 column_default 为空 = 有问题（需要同样处理）
SELECT table_name, column_name, is_identity, identity_generation, column_default
FROM information_schema.columns
WHERE column_name = 'id'
  AND table_name IN ('qc_records','qc_images','qc_image_snapshots','qc_shares',
                     'qc_confirmations','qc_options','qc_staffs','qc_shops')
ORDER BY table_name;

-- 4) 验证：无真实写入的干跑（回滚，不会留数据）
--    注意：线上表 shop 为 NOT NULL，验证行需带上 shop
BEGIN;
INSERT INTO qc_records (staff, shop, date, problem)
VALUES ('__诊断__', '__诊断__', '2026-09-04', '自增验证，即将回滚');
ROLLBACK;
-- 成功标志：Results 无红色报错（INSERT 后随即回滚，不留数据）
