-- 重新导入 176 款花色数据
INSERT INTO pattern_assets (brand, type, name, series, color, diameter, color_diameter, material, oxygen, water, spec, lens_img, eye_img, description) VALUES
  ('弥生', '日抛', '玻璃娃娃', '少女漫-日抛', '黑', '14.5', '14', '', '', '', '', 'images/patterns/misho_daily_玻璃娃娃_lens.jpg', '', ''),
  ('弥生', '日抛', '绿野仙棕', '少女漫-日抛', '棕', '14', '13.4', '', '', '', '', 'images/patterns/misho_daily_绿野仙棕_lens.jpg', '', '红棕色外圈+点状式绿色内圈，从中心向外由深至浅自然过渡，外圈柔化锁边与原生瞳孔完美融合，素颜也能 hold 住'),
  ('弥生', '日抛', '小棕环pro', '少女漫-日抛', '棕+有锁边', '14.2', '13.6', '', '', '', '', 'images/patterns/misho_daily_小棕环pro_lens.jpg', 'images/patterns/misho_daily_小棕环pro_eye.jpg', '这款【小棕环pro】比自然款更有心机的棕色水珠，季节百搭、妆容百搭，即温柔又显嫩~'),
  ('弥生', '日抛', '小黑环pro', '少女漫-日抛', '黑+有锁边', '14.2', '13.74', '', '', '', '', 'images/patterns/misho_daily_小黑环pro_lens.jpg', 'images/patterns/misho_daily_小黑环pro_eye.jpg', '这款【小黑环pro】上眼是原生感的黑亮瞳，自然扩瞳不夸张，素颜戴也像天生的透亮黑眼珠～'),
  ('弥生', '日抛', '妮妮千金', '少女漫-日抛', '同款半年抛转日抛', '14.5', '14', '', '', '', '', '', 'images/patterns/misho_daily_妮妮千金_eye.jpg', '这款是属于氛围感眼珠珠，约会必备，戴上像在眼睛里打了腮红~'),
  ('弥生', '日抛', '摆烂海星', '人鱼系列日抛', '亚裔棕', '14.5', '14', '', '', '', '', 'images/patterns/misho_daily_摆烂海星_lens.jpg', 'images/patterns/misho_daily_摆烂海星_eye.jpg', '这款花色外圈采用长短不一的放射性纹路，上眼自带亚裔感的深邃混血感，自然扩瞳不夸张，是一眼就有 “美式甜心” 既视感的原生棕瞳✨'),
  ('弥生', '日抛', '海想豹豹', '人鱼系列日抛', '雾蓝', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_daily_海想豹豹_lens.jpg', 'images/patterns/misho_daily_海想豹豹_eye.jpg', '这款雾蓝调裹着清透柔雾，是一眼就沦陷的 “雾蓝清冷瞳”✨'),
  ('弥生', '日抛', '一夜鲍富', '人鱼系列日抛', '琥珀棕', '14.2', '14.2', '', '', '', '', 'images/patterns/misho_daily_一夜鲍富_lens.jpg', 'images/patterns/misho_daily_一夜鲍富_eye.jpg', '这款是琥珀棕调，暖调氛围感，自然扩瞳不夸张~'),
  ('弥生', '日抛', '企鹅妮妮', '人鱼系列日抛', '区别于妮妮千金，锁边是有纹理层次，粉色占比更高，高光更亮', '14.5', '13.9', '', '', '', '', '', 'images/patterns/misho_daily_企鹅妮妮_eye.jpg', '这款是粉紫调融着通透光泽，上眼像把葡萄冻的粉紫碎光揉进瞳里的甜妹氛围感~'),
  ('弥生', '日抛', '浮游记忆', '人鱼系列日抛', '黑（和蔚蓝契约同款不同色）', '14.2', '13.6', '', '', '', '', 'images/patterns/misho_daily_浮游记忆_lens.jpg', 'images/patterns/misho_daily_浮游记忆_eye.jpg', '【浮游记忆】黑色小直径款上新啦，一口“糯叽叽的黑糖珍珠”美瞳，伪素颜必杀技！不死板的原生感超绝，带个美瞳就能出门～'),
  ('弥生', '日抛', '泡沫挽歌', '人鱼系列日抛', '棕', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_daily_泡沫挽歌_lens.jpg', 'images/patterns/misho_daily_泡沫挽歌_eye.jpg', '泡沫挽歌：古早台妹风，上眼比较有古早芭比感，棕色锁边让花纹整体都像，奶茶焦糖琥珀棕。'),
  ('弥生', '日抛', '蔚蓝契约', '人鱼系列日抛', '蓝（和浮游记忆同款不同色）', '14.2', '13.6', '', '', '', '', 'images/patterns/misho_daily_蔚蓝契约_lens.jpg', 'images/patterns/misho_daily_蔚蓝契约_eye.jpg', '蔚蓝契约：静谧而温柔的深海蓝色，简单干净才是伪素颜的关键、水光透亮，蓝色超级显白，黄皮修正液~'),
  ('弥生', '日抛', '微醺海浪', '人鱼系列日抛', '棕（弥生女高窗外樱花、伦敦碎片的同款不同色。）', '14.5', '13.81', '', '', '', '', 'images/patterns/misho_daily_微醺海浪_lens.jpg', 'images/patterns/misho_daily_微醺海浪_eye.jpg', '微醺海浪：爆款花色同款不同色哒，真正的水珠感款式，柔棕调上眼像玻璃珠一样清透融瞳，眼神温柔又有氛围感~'),
  ('弥生', '日抛', '草莓大福', '花厨小熊-日抛', '棕粉', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_daily_草莓大福_lens.jpg', 'images/patterns/misho_daily_草莓大福_eye.jpg', '外圈棕色的细锁边+内圈浅粉色小高光使得眼睛更加立体及温柔'),
  ('弥生', '日抛', '焦糖熔岩', '花厨小熊-日抛', '棕', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_daily_焦糖熔岩_lens.jpg', 'images/patterns/misho_daily_焦糖熔岩_eye.jpg', '柔润深棕底色自带通透感，上眼像把焦糖蜜色揉进瞳里，自然扩瞳不夸张，是素颜也能驾驭的 “妈生感暖棕瞳”✨'),
  ('弥生', '日抛', '快乐小狗', '花厨小熊-日抛', '黑', '14.5', '14.15', '', '', '', '', 'images/patterns/misho_daily_快乐小狗_lens.jpg', 'images/patterns/misho_daily_快乐小狗_eye.jpg', '宝子~这款【快乐小狗】上眼简直就是一颗黑曜石，黑色锁边不生硬，搭配内圈黑灰色的花纹很有个性~'),
  ('弥生', '日抛', '黄油小熊', '花厨小熊-日抛', '棕', '14.5', '14.15', '', '', '', '', 'images/patterns/misho_daily_黄油小熊_lens.jpg', 'images/patterns/misho_daily_黄油小熊_eye.jpg', '这款【黄油小熊】外圈偏黑色自然放大，内圈棕色高光，让眼神软糯又明亮~'),
  ('弥生', '日抛', '蜂蜜罐罐', '花厨小熊-日抛', '棕', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_daily_蜂蜜罐罐_lens.jpg', 'images/patterns/misho_daily_蜂蜜罐罐_eye.jpg', '这款花色是暖棕调美瞳，融瞳自然，眼神温柔又透亮，超适合秋冬佩戴~'),
  ('弥生', '日抛', '糖霜可可', '花厨小熊-日抛', '黑灰+亮点', '14.5', '14.3', '', '', '', '', 'images/patterns/misho_daily_糖霜可可_lens.jpg', 'images/patterns/misho_daily_糖霜可可_eye.jpg', '【糖霜可可】神秘黑灰波纹，叠加细腻珠光，让眼神如水波般灵动深邃'),
  ('弥生', '半年抛', '白月光', '心动调频', '黑灰', '14.2', '13.5', '', '', '', '', 'images/patterns/misho_halfyear_白月光_lens.jpg', 'images/patterns/misho_halfyear_白月光_eye.jpg', '【白月光】雾感清透黑灰，自然融瞳的清冷白月光眼~'),
  ('弥生', '半年抛', '蓝调时分', '心动调频', '蓝', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_蓝调时分_lens.jpg', 'images/patterns/misho_halfyear_蓝调时分_eye.jpg', '蓝调时分：深邃冰感蓝，自带混血感的清冷雾蓝瞳'),
  ('弥生', '半年抛', '摩卡奶茶', '心动调频', '奶棕', '14.2', '13.6', '', '', '', '', 'images/patterns/misho_halfyear_摩卡奶茶_lens.jpg', 'images/patterns/misho_halfyear_摩卡奶茶_eye.jpg', '摩卡奶茶：柔润暖棕调，温柔又日常的妈生感奶茶瞳'),
  ('弥生', '半年抛', '千禧校花', '心动调频', '黑灰', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_千禧校花_lens.jpg', 'images/patterns/misho_halfyear_千禧校花_eye.jpg', '千禧校花：黑亮扩瞳款，自带水光感的无辜黑亮眼'),
  ('弥生', '半年抛', '桃气闪闪', '心动调频', '闪粉', '14.2', '13.7', '', '', '', '', 'images/patterns/misho_halfyear_桃气闪闪_lens.jpg', 'images/patterns/misho_halfyear_桃气闪闪_eye.jpg', '桃气闪闪：甜粉紫带细闪，自带少女感的软萌粉紫瞳'),
  ('弥生', '半年抛', '全息悸动', '初音未来', '在逃公主同款蓝色', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_全息悸动_lens.jpg', 'images/patterns/misho_halfyear_全息悸动_eye.jpg', '这款「全息悸动」✨ 葱色光波漫入眼眸，复刻初音未来的清透蓝瞳，自带次元柔光感~'),
  ('弥生', '半年抛', '指尖蝶舞', '初音未来', '深海蓝', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_指尖蝶舞_lens.jpg', 'images/patterns/misho_halfyear_指尖蝶舞_eye.jpg', '这款是蝶翼清透深海蓝瞳，还原公式级二次元灵动眼妆~'),
  ('弥生', '半年抛', '39°巡光', '初音未来', '冷感蓝', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_halfyear_39°巡光_lens.jpg', 'images/patterns/misho_halfyear_39°巡光_eye.jpg', '39° 巡光・初音款｜清透冷感蓝调 + 对称高光，自带舞台打光感~'),
  ('弥生', '半年抛', '爱的无限曲', '初音未来', '暖棕琥珀调', '14.5', '14.3', '', '', '', '', 'images/patterns/misho_halfyear_爱的无限曲_lens.jpg', 'images/patterns/misho_halfyear_爱的无限曲_eye.jpg', '这款是暖棕琥珀瞳！爱的无限曲自带温柔氛围感，适配初音软萌感~'),
  ('弥生', '半年抛', '薄荷微光', '初音未来', '青绿', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_薄荷微光_lens.jpg', 'images/patterns/misho_halfyear_薄荷微光_eye.jpg', '这款薄荷微光，薄荷青调瞳色，像虚拟舞台上的粼粼碎光~'),
  ('弥生', '半年抛', '落日漫游', '初音未来', '甜酷棕', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_落日漫游_lens.jpg', 'images/patterns/misho_halfyear_落日漫游_eye.jpg', '这款【落日漫游】清透棕调 + 细腻高光，还原温柔次元眼！'),
  ('弥生', '半年抛', '虚拟泪光', '初音未来', '经典黑', '14.5', '14.3', '', '', '', '', 'images/patterns/misho_halfyear_虚拟泪光_lens.jpg', 'images/patterns/misho_halfyear_虚拟泪光_eye.jpg', '这款是超自然的通透黑瞳 + 细腻高光，还原二次元的纯欲泪光感~'),
  ('弥生', '半年抛', '甜心主唱', '初音未来', '樱花粉', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_甜心主唱_lens.jpg', 'images/patterns/misho_halfyear_甜心主唱_eye.jpg', '【甜心主唱】樱花粉调瞳色，把虚拟偶像的甜酷感揉进眼里~'),
  ('弥生', '半年抛', '乌托邦幻想', '初音未来', '梦幻紫', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_乌托邦幻想_lens.jpg', 'images/patterns/misho_halfyear_乌托邦幻想_eye.jpg', '这款是雾紫柔光瞳，像虚拟世界里的浪漫幻梦~'),
  ('弥生', '半年抛', '国民初恋', '心动信号', '', '14.2', '13.3', '', '', '', '', 'images/patterns/misho_halfyear_国民初恋_lens.jpg', 'images/patterns/misho_halfyear_国民初恋_eye.jpg', '黑色细锁边外圈配上黑灰色有一种水汪汪的、湿漉漉的无辜感，比单纯的黑更灵动，更让人心动~'),
  ('弥生', '半年抛', '转校千金', '心动信号', '', '14.2', '13.7', '', '', '', '', 'images/patterns/misho_halfyear_转校千金_lens.jpg', 'images/patterns/misho_halfyear_转校千金_eye.jpg', '外圈采用黑灰色细锁边，内圈采用深灰色放射性花纹，让花色在放大眼睛的同时更加有混血感~'),
  ('弥生', '半年抛', '告白汽水', '心动信号', '', '14.2', '13.6', '', '', '', '', 'images/patterns/misho_halfyear_告白汽水_lens.jpg', 'images/patterns/misho_halfyear_告白汽水_eye.jpg', '这款是低饱和的蓝灰色调+细闪打造出清澈透亮、自带呼吸感的眼睛。'),
  ('弥生', '半年抛', '栗栗在逃', '心动信号', '', '14.2', '13.6', '', '', '', '', 'images/patterns/misho_halfyear_栗栗在逃_lens.jpg', 'images/patterns/misho_halfyear_栗栗在逃_eye.jpg', '整体以暖金棕色基底，内圈浅棕色高光使得外圈锁边更佳明显，但过渡自然，实现温柔放大双眼缺不死板'),
  ('弥生', '半年抛', '蓝朋友', '心动信号', '', '14.2', '13.5', '', '', '', '', 'images/patterns/misho_halfyear_蓝朋友_lens.jpg', 'images/patterns/misho_halfyear_蓝朋友_eye.jpg', '这款深蓝色外圈过渡更加自然，内有细腻花纹点亮眼神！把精致直接刻在瞳孔里，近看才能发现的高级感，让眼睛自带故事感。'),
  ('弥生', '半年抛', '夏吻野火', '随便花系列', '灰咖', '14.2', '13.65', '', '', '', '', 'images/patterns/misho_halfyear_夏吻野火_lens.jpg', 'images/patterns/misho_halfyear_夏吻野火_eye.jpg', '这款是雾感咖灰美瞳！柔雾渐变外圈，自然柔和放大双眼，伪素颜白开水清透瞳，通勤淡妆万能款～'),
  ('弥生', '半年抛', '晚熟游戏', '随便花系列', '黑灰+亮点', '14.5', '14.3', '', '', '', '', 'images/patterns/misho_halfyear_晚熟游戏_lens.jpg', 'images/patterns/misho_halfyear_晚熟游戏_eye.jpg', '【晚熟游戏】黑色外圈精致锁边，浅灰底色搭配若隐若现的紫色线条，上眼清冷又灵动，氛围感直接拉满～'),
  ('弥生', '半年抛', '月光骑士', '随便花系列', '黑蓝色', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_月光骑士_lens.jpg', 'images/patterns/misho_halfyear_月光骑士_eye.jpg', '【月光骑士】冷调黑蓝交织，外圈深邃锁边，上眼清冷又神秘，宛如月光下的骑士眼眸～'),
  ('弥生', '半年抛', '暧昧戏法', '随便花系列', '棕', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_暧昧戏法_lens.jpg', 'images/patterns/misho_halfyear_暧昧戏法_eye.jpg', ''),
  ('弥生', '半年抛', '柏林热吻', '随便花系列', '棕', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_柏林热吻_lens.jpg', 'images/patterns/misho_halfyear_柏林热吻_eye.jpg', ''),
  ('弥生', '半年抛', '情绪玩家', '随便花系列', '蓝色', '14.2', '13.5', '', '', '', '', 'images/patterns/misho_halfyear_情绪玩家_lens.jpg', 'images/patterns/misho_halfyear_情绪玩家_eye.jpg', ''),
  ('弥生', '半年抛', '初生玫瑰', '随便花系列', '偏粉+拼色', '14.2', '13.3', '', '', '', '', 'images/patterns/misho_halfyear_初生玫瑰_lens.jpg', 'images/patterns/misho_halfyear_初生玫瑰_eye.jpg', '【初生玫瑰】柔粉调融瞳自然，眼神自带温柔滤镜~'),
  ('弥生', '半年抛', '月光恋人', '随便花系列', '蓝紫', '14.2', '13.5', '', '', '', '', 'images/patterns/misho_halfyear_月光恋人_lens.jpg', '', ''),
  ('弥生', '半年抛', '南韩千金', '随便花系列', '浅蓝', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_南韩千金_lens.jpg', '', '恰到好处的蓝，既不张扬又极具辨识度，日常戴显温柔，化妆戴更出彩，适配各种风格妆容哟~'),
  ('弥生', '半年抛', '冷雾茶黑', '随便花系列', '黑', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_halfyear_冷雾茶黑_lens.jpg', 'images/patterns/misho_halfyear_冷雾茶黑_eye.jpg', '宝宝~这款冷雾茶黑的看下哟，透透的大直径眼珠珠～戴上秒变无辜大眼，黑色超自然显幼态~'),
  ('弥生', '半年抛', '笨蛋美女', '随便花系列', '棕', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_halfyear_笨蛋美女_lens.jpg', 'images/patterns/misho_halfyear_笨蛋美女_eye.jpg', '宝宝~推荐这款笨蛋美女的，日常通勤必买单品 又纯又欲水光瞳，很温柔细腻'),
  ('弥生', '半年抛', '爽文女主', '随便花系列', '棕+金粉', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_爽文女主_lens.jpg', 'images/patterns/misho_halfyear_爽文女主_eye.jpg', '这款棕瞳增大双眼效果明显，但又不会夸张突兀，让眼睛瞬间有神又灵动~'),
  ('弥生', '半年抛', '南洋水珠pro', '随便花系列', '琥珀棕', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_南洋水珠pro_lens.jpg', 'images/patterns/misho_halfyear_南洋水珠pro_eye.jpg', '【南洋水珠】琥珀瞳仁是最近的新宠，通透少女感十足~'),
  ('弥生', '半年抛', '天菜女友', '随便花系列', '灰绿', '14.5', '13.9', '', '', '', '', 'images/patterns/misho_halfyear_天菜女友_lens.jpg', 'images/patterns/misho_halfyear_天菜女友_eye.jpg', '清冷美女必备款【天菜女友】~绿色宝石眼珠珠超推荐！'),
  ('弥生', '半年抛', '水星记', '随便花系列', '蓝', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_水星记_lens.jpg', 'images/patterns/misho_halfyear_水星记_eye.jpg', '宝宝~推荐这款水星记的，这个蓝色的透度真的好绝！超火的一款蓝色美瞳，相信宝贝戴了一定会爱上~'),
  ('弥生', '半年抛', '成为自己', '随便花系列', '棕', '14.5', '13.82', '', '', '', '', 'images/patterns/misho_halfyear_成为自己_lens.jpg', 'images/patterns/misho_halfyear_成为自己_eye.jpg', '【成为自己】，暖棕调融瞳自然，眼神温柔又有气场'),
  ('弥生', '半年抛', '半熟幻想', '随便花系列', '棕', '14.5', '13.6', '', '', '', '', 'images/patterns/misho_halfyear_半熟幻想_lens.jpg', 'images/patterns/misho_halfyear_半熟幻想_eye.jpg', '随便花新品上线
半熟幻想 14.5mm'),
  ('弥生', '半年抛', '蓝岛时刻', '随便花系列', '深蓝', '14.5', '13.9', '', '', '', '', 'images/patterns/misho_halfyear_蓝岛时刻_lens.jpg', 'images/patterns/misho_halfyear_蓝岛时刻_eye.jpg', '深邃牛仔蓝
蓝岛时刻 14.5mm'),
  ('弥生', '半年抛', '富婆人生', '随便花系列', '棕', '14.5', '13.73', '', '', '', '', 'images/patterns/misho_halfyear_富婆人生_lens.jpg', 'images/patterns/misho_halfyear_富婆人生_eye.jpg', '【富婆人生】清冷灰棕调，眼神贵气又吸睛'),
  ('弥生', '半年抛', '恋爱循环', '随便花系列', '蓝', '14.5', '13.77', '', '', '', '', 'images/patterns/misho_halfyear_恋爱循环_lens.jpg', 'images/patterns/misho_halfyear_恋爱循环_eye.jpg', ''),
  ('弥生', '半年抛', '换乘恋爱', '随便花系列', '黑色版【天菜女友】', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_换乘恋爱_lens.jpg', 'images/patterns/misho_halfyear_换乘恋爱_eye.jpg', '天菜同款黑色【换乘恋爱】，独特的花纹百搭自然款~'),
  ('弥生', '半年抛', '巴洛克玫瑰', '随便花系列', '紫色', '14.5', '13.95', '', '', '', '', 'images/patterns/misho_halfyear_巴洛克玫瑰_lens.jpg', 'images/patterns/misho_halfyear_巴洛克玫瑰_eye.jpg', '【巴洛克玫瑰】少女无法拒绝的梦幻紫~紫色超温柔有韵味'),
  ('弥生', '半年抛', '航海日记', '随便花系列', '蓝', '14.5', '13.95', '', '', '', '', 'images/patterns/misho_halfyear_航海日记_lens.jpg', 'images/patterns/misho_halfyear_航海日记_eye.jpg', ''),
  ('弥生', '半年抛', '小野猫', '随便花系列', '棕', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_小野猫_lens.jpg', 'images/patterns/misho_halfyear_小野猫_eye.jpg', '宝宝~这款【小野猫】可爱又灵动的棕色大直径，日常通勤百搭款~'),
  ('弥生', '半年抛', '清晨解药', '随便花系列', '灰色', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_halfyear_清晨解药_lens.jpg', 'images/patterns/misho_halfyear_清晨解药_eye.jpg', '【清晨解药】甜酷灰色，百搭日常一丢丢混血'),
  ('弥生', '半年抛', '奶油黑客', '随便花系列', '黑色', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_奶油黑客_lens.jpg', 'images/patterns/misho_halfyear_奶油黑客_eye.jpg', '【奶油黑客】，黑调融细闪，清透自然，眼神自带雾面滤镜~'),
  ('弥生', '半年抛', '反骨甜心', '随便花系列', '紫色', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_反骨甜心_lens.jpg', 'images/patterns/misho_halfyear_反骨甜心_eye.jpg', '浅紫调自带梦幻滤镜，像把薰衣草花海揉进眼眸， 上眼清透又神秘，仿佛藏着一整片银河，温柔中带点清冷疏离感，妥妥的人间紫水晶特效~'),
  ('弥生', '半年抛', '冷雾茶棕', '随便花系列', '棕色', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_halfyear_冷雾茶棕_lens.jpg', 'images/patterns/misho_halfyear_冷雾茶棕_eye.jpg', '冷雾茶棕 Dia:14.5mm
好自然的琥珀棕瞳'),
  ('弥生', '半年抛', '偷藏月光', '随便花系列', '黑粉', '14.5', '14.3', '', '', '', '', 'images/patterns/misho_halfyear_偷藏月光_lens.jpg', 'images/patterns/misho_halfyear_偷藏月光_eye.jpg', '温柔粉棕调，上眼清透又空灵，自带柔光滤镜，仿佛藏着一汪清甜的晨露，无辜感拉满，妥妥的人间洋娃娃花色～'),
  ('弥生', '半年抛', '落日橘子海', '随便花系列', '黑棕', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_halfyear_落日橘子海_lens.jpg', 'images/patterns/misho_halfyear_落日橘子海_eye.jpg', '【落日橘子海】融瞳自然，眼神自带温柔氛围感'),
  ('弥生', '半年抛', '妮妮千金', '女高系列', '黑粉', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_妮妮千金_lens.jpg', 'images/patterns/misho_halfyear_妮妮千金_eye.jpg', ''),
  ('弥生', '半年抛', '造梦乐园', '女高系列', '青灰', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_造梦乐园_lens.jpg', 'images/patterns/misho_halfyear_造梦乐园_eye.jpg', '这款美瞳青灰调裹着雾感，戴上感觉清透又带点疏离感，大直径扩瞳自带清冷滤镜，是一眼就沦陷的 “青灰雾感眼”✨'),
  ('弥生', '半年抛', '气泡葡萄', '女高系列', '紫色', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_halfyear_气泡葡萄_lens.jpg', 'images/patterns/misho_halfyear_气泡葡萄_eye.jpg', '这款深紫色调的美瞳，比自然款更魅惑 比混血款更温柔，戴上是一眼就心动的 “葡萄冻冻眼”✨~'),
  ('弥生', '半年抛', '黑莓缪斯', '女高系列', '黑', '14.2', '13.67', '', '', '', '', 'images/patterns/misho_halfyear_黑莓缪斯_lens.jpg', 'images/patterns/misho_halfyear_黑莓缪斯_eye.jpg', '这款花色是黑色锁边+黑灰调内圈，无声放大双眼，眼神立刻变得清澈有神，像天生的好底子，自然到老师、上司都看不出你戴了美瞳！'),
  ('弥生', '半年抛', '她的梨涡', '女高系列', '棕', '14.2', '13.4', '', '', '', '', 'images/patterns/misho_halfyear_她的梨涡_lens.jpg', 'images/patterns/misho_halfyear_她的梨涡_eye.jpg', '小直径终于有棕色自然款啦，可配合日常淡妆、伪素颜~日常通勤、上学、见长辈都可戴~'),
  ('弥生', '半年抛', '我喜欢你', '女高系列', '灰', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_我喜欢你_lens.jpg', 'images/patterns/misho_halfyear_我喜欢你_eye.jpg', '适合淡颜系的新品眼珠【我喜欢ni】'),
  ('弥生', '半年抛', '你的名字', '女高系列', '棕色', '14.5', '13.88', '', '', '', '', 'images/patterns/misho_halfyear_你的名字_lens.jpg', 'images/patterns/misho_halfyear_你的名字_eye.jpg', '宝子~推荐这款【ni的名字】温柔到骨子里的初恋眼，日常通勤必买单品~'),
  ('弥生', '半年抛', '校花指南', '女高系列', '蓝色', '14.5', '14.06', '', '', '', '', 'images/patterns/misho_halfyear_校花指南_lens.jpg', 'images/patterns/misho_halfyear_校花指南_eye.jpg', '【校花指南】清冷蓝调，眼神亮眼又吸睛'),
  ('弥生', '半年抛', '汪汪队', '女高系列', '黑色【冷雾茶黑同款小直径】', '14.2', '13.7', '', '', '', '', 'images/patterns/misho_halfyear_汪汪队_lens.jpg', 'images/patterns/misho_halfyear_汪汪队_eye.jpg', '水润润乖乖女必备，招牌花色清透小奶黑，喜欢不要错过哟~'),
  ('弥生', '半年抛', '夜与法兰西', '女高系列', '黑色', '14.5', '13.9', '', '', '', '', 'images/patterns/misho_halfyear_夜与法兰西_lens.jpg', 'images/patterns/misho_halfyear_夜与法兰西_eye.jpg', '这款【夜与法兰西】，洋娃娃专属漫画大眼哟'),
  ('弥生', '半年抛', '元气女高', '女高系列', '灰色', '14.2', '13.4', '', '', '', '', 'images/patterns/misho_halfyear_元气女高_lens.jpg', 'images/patterns/misho_halfyear_元气女高_eye.jpg', '元气感满满~氛围感混血珠珠'),
  ('弥生', '半年抛', '少女心事', '女高系列', '紫色', '14.5', '13.9', '', '', '', '', 'images/patterns/misho_halfyear_少女心事_lens.jpg', 'images/patterns/misho_halfyear_少女心事_eye.jpg', '少女心事14.5mm，低饱和度紫灰色~上眼秒变温柔美少女~'),
  ('弥生', '半年抛', '千禧莓莓', '女高系列', '粉棕', '14.5', '13.9', '', '', '', '', 'images/patterns/misho_halfyear_千禧莓莓_lens.jpg', 'images/patterns/misho_halfyear_千禧莓莓_eye.jpg', '宝子~看下这款又泰又嗲的眼珠珠-千禧莓莓'),
  ('弥生', '半年抛', '甜断记忆', '女高系列', '棕色', '14.5', '13.9', '', '', '', '', 'images/patterns/misho_halfyear_甜断记忆_lens.jpg', 'images/patterns/misho_halfyear_甜断记忆_eye.jpg', '甜断记忆
扑面而来的少女气息，粉棕色让你的妆容更出彩，日常不化妆也可以戴的自然款'),
  ('弥生', '半年抛', '甜宠学妹', '女高系列', '粉色', '14.2', '12.9', '', '', '', '', 'images/patterns/misho_halfyear_甜宠学妹_lens.jpg', 'images/patterns/misho_halfyear_甜宠学妹_eye.jpg', '戴上就是超级温柔的粉紫色，14.20mm的直径自然放大双眼~'),
  ('弥生', '半年抛', '冰岛日记', '女高系列', '黑色', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_冰岛日记_lens.jpg', 'images/patterns/misho_halfyear_冰岛日记_eye.jpg', '【冰岛日记】颜色是浓郁醇厚的巧克力棕，自然又百搭，素颜戴毫无压力，轻松打造妈生感美眸，适配各种妆容风格，日常通勤、约会出游都超合适哒~'),
  ('弥生', '半年抛', '伦敦碎片', '女高系列', '黑灰', '14.5', '13.92', '', '', '', '', 'images/patterns/misho_halfyear_伦敦碎片_lens.jpg', 'images/patterns/misho_halfyear_伦敦碎片_eye.jpg', '弥生新花色来啦【伦敦碎片】，显色又有漫画感~尊嘟好看~'),
  ('弥生', '半年抛', '加州校园', '女高系列', '棕色', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_halfyear_加州校园_lens.jpg', 'images/patterns/misho_halfyear_加州校园_eye.jpg', '宝子~这款美瞳一戴，整个气质都提升了好几个档次，清冷又高级~'),
  ('弥生', '半年抛', '暗恋无果', '女高系列', '墨绿+拼色', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_暗恋无果_lens.jpg', 'images/patterns/misho_halfyear_暗恋无果_eye.jpg', '【暗恋无果】森系墨绿调，融瞳自然，眼神清冷又勾人'),
  ('弥生', '半年抛', '甜蜜暗号', '女高系列', '棕色', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_甜蜜暗号_lens.jpg', 'images/patterns/misho_halfyear_甜蜜暗号_eye.jpg', '浅棕主调温柔又清透，眼里藏着蜜糖般的清甜 ，自带初恋感 buff ，日常又纯欲，谁戴谁是人间水蜜桃～'),
  ('弥生', '半年抛', '心动信号', '女高系列', '粉棕', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_心动信号_lens.jpg', 'images/patterns/misho_halfyear_心动信号_eye.jpg', '【心动信号】清透又带点朦胧雾感，上眼瞬间眼神会 “发电”，温柔钓系氛围拉满，谁戴谁是纯欲心动制造机~'),
  ('弥生', '半年抛', '初恋小事', '女高系列', '灰色', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_初恋小事_lens.jpg', 'images/patterns/misho_halfyear_初恋小事_eye.jpg', '上眼水灵灵的小鹿眼，有种清纯女高的幼态感~'),
  ('弥生', '半年抛', '窗外樱花', '女高系列', '棕色', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_窗外樱花_lens.jpg', 'images/patterns/misho_halfyear_窗外樱花_eye.jpg', '【窗外樱花】柔棕调融瞳自然，眼神温柔似樱花'),
  ('弥生', '半年抛', '等你下课', '女高系列', '棕色', '14.5', '14.3', '', '', '', '', 'images/patterns/misho_halfyear_等你下课_lens.jpg', 'images/patterns/misho_halfyear_等你下课_eye.jpg', '【等你下课】暖棕带细闪，眼神温柔又灵动'),
  ('弥生', '半年抛', '闪闪自信', '女高系列', '蓝', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_闪闪自信_lens.jpg', 'images/patterns/misho_halfyear_闪闪自信_eye.jpg', '【闪闪自信】戴上后眼睛瞬间有了深邃感，仿佛藏着无尽故事，自然又好看'),
  ('弥生', '半年抛', '玻璃娃娃', '少女漫系列', '灰黑', '14.5', '14', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '溺爱冰河', '少女漫系列', '蓝', '14.5', '14.3', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '恶女千金', '少女漫系列', '红色', '14.5', '13.9', '', '', '', '', 'images/patterns/misho_halfyear_恶女千金_lens.jpg', 'images/patterns/misho_halfyear_恶女千金_eye.jpg', '红棕调超吸睛，眼神又 A 又飒'),
  ('弥生', '半年抛', '魔女眼泪', '少女漫系列', '蓝色', '14.5', '13.7', '', '', '', '', '', 'images/patterns/misho_halfyear_魔女眼泪_eye.jpg', ''),
  ('弥生', '半年抛', '水漾狂想曲', '少女漫系列', '蓝绿', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_水漾狂想曲_lens.jpg', 'images/patterns/misho_halfyear_水漾狂想曲_eye.jpg', '超推荐的【水漾狂想曲】，清新蓝绿搭配~买回去出去玩拍照超有氛围哒~90%客户已购的大爆款！'),
  ('弥生', '半年抛', '蓝色圆舞曲', '少女漫系列', '蓝色', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_蓝色圆舞曲_lens.jpg', 'images/patterns/misho_halfyear_蓝色圆舞曲_eye.jpg', '漫画感眼珠珠【蓝色圆舞曲】，上眼一秒拥有滤镜般水光大眼睛~'),
  ('弥生', '半年抛', '无人区玫瑰', '少女漫系列', '粉棕', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_无人区玫瑰_lens.jpg', 'images/patterns/misho_halfyear_无人区玫瑰_eye.jpg', '断货款【无人区玫瑰】仙气飘飘的粉色瞳~增添温柔情调'),
  ('弥生', '半年抛', '在逃公主', '少女漫系列', '粉+拼色', '14.2', '13.36', '', '', '', '', '', '', '【在逃公主】粉紫调，眼神温柔似童话'),
  ('弥生', '半年抛', '在逃公主pro', '少女漫系列', '', '14.5', '14.35', '', '', '', '', 'images/patterns/misho_halfyear_在逃公主pro_lens.jpg', 'images/patterns/misho_halfyear_在逃公主pro_eye.jpg', ''),
  ('弥生', '半年抛', '心动降临', '少女漫系列', '粉色', '14.5', '13.83', '', '', '', '', 'images/patterns/misho_halfyear_心动降临_lens.jpg', '', '粉紫色新品花色，叫姐同款心动降临，好有氛围感的眼珠珠~'),
  ('弥生', '半年抛', '月光鸣奏曲', '少女漫系列', '棕', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_月光鸣奏曲_lens.jpg', '', '新品琥珀色棕色瞳~叫姐同款花色'),
  ('弥生', '半年抛', '爱神降临', '少女漫系列', '棕+微粉', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_爱神降临_lens.jpg', 'images/patterns/misho_halfyear_爱神降临_eye.jpg', '这款【爱神降临】纯欲风~大直径超可爱百搭的款'),
  ('弥生', '半年抛', '月亮危机', '少女漫系列', '黑+金粉', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_halfyear_月亮危机_lens.jpg', 'images/patterns/misho_halfyear_月亮危机_eye.jpg', '黑色美瞳推荐这款【月亮危机】，婴儿般透亮黑色大眼，水灵透亮~上眼不呆板'),
  ('弥生', '半年抛', '龙颜芭比', '少女漫系列', '粉', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_龙颜芭比_lens.jpg', 'images/patterns/misho_halfyear_龙颜芭比_eye.jpg', ''),
  ('弥生', '半年抛', '星光降落', '少女漫系列', '拼色', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_halfyear_星光降落_lens.jpg', 'images/patterns/misho_halfyear_星光降落_eye.jpg', '新品星光降落..仿佛眼里有星河~'),
  ('弥生', '半年抛', '指尖魔法', '少女漫系列', '棕色', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_halfyear_指尖魔法_lens.jpg', 'images/patterns/misho_halfyear_指尖魔法_eye.jpg', '淡颜宝宝的加分神器，新手盲选不出错的棕色水珠款，人畜无害乖乖女'),
  ('弥生', '半年抛', '虚空蔷薇', '少女漫系列', '紫色', '14.5', '14.29', '', '', '', '', 'images/patterns/misho_halfyear_虚空蔷薇_lens.jpg', 'images/patterns/misho_halfyear_虚空蔷薇_eye.jpg', '自带清冷感，超级显白的紫色玻璃珠，深瞳也完全不用担心！'),
  ('弥生', '半年抛', '仲夏夜探戈', '少女漫系列', '紫色【水漾狂想曲同款】', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_仲夏夜探戈_lens.jpg', 'images/patterns/misho_halfyear_仲夏夜探戈_eye.jpg', '水漾同款紫色【仲夏夜探戈】，神秘柔紫调，一戴自带梦幻滤镜，眼神像藏了仲夏夜星光，纯欲又魅惑~'),
  ('弥生', '半年抛', '玛丽皇后', '少女漫系列', '紫色', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_halfyear_玛丽皇后_lens.jpg', 'images/patterns/misho_halfyear_玛丽皇后_eye.jpg', '【玛丽皇后】，神秘柔紫调，自带高贵滤镜，眼神秒变优雅宫廷风，纯欲又贵气'),
  ('弥生', '半年抛', '超大宝宝棕', '少女漫系列', '棕色', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_超大宝宝棕_lens.jpg', 'images/patterns/misho_halfyear_超大宝宝棕_eye.jpg', '“超大宝宝棕” ，暖棕调，眼神澄澈又显乖'),
  ('弥生', '半年抛', '超大渣渣黑', '少女漫系列', '黑色', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_超大渣渣黑_lens.jpg', 'images/patterns/misho_halfyear_超大渣渣黑_eye.jpg', '【超大渣渣黑】，一戴秒变无辜狗狗眼，纯欲又扩瞳，眼神直接锁住心动感~'),
  ('弥生', '半年抛', '超大奶芙芙', '少女漫系列', '棕+金粉', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_超大奶芙芙_lens.jpg', 'images/patterns/misho_halfyear_超大奶芙芙_eye.jpg', '“超大奶芙芙”温柔奶棕调。眼神像裹了层棉花糖，纯欲感直接拉满~'),
  ('弥生', '半年抛', '超大椰椰灰', '少女漫系列', '灰蓝', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_超大椰椰灰_lens.jpg', 'images/patterns/misho_halfyear_超大椰椰灰_eye.jpg', '“超大椰椰灰”清冷灰调自带松弛感，一戴秒变混血感，眼神像椰灰拿铁般高级，纯欲又清冷~'),
  ('弥生', '半年抛', '超大酥酥绿', '少女漫系列', '绿+金粉', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_超大酥酥绿_lens.jpg', 'images/patterns/misho_halfyear_超大酥酥绿_eye.jpg', '“超大酥酥绿” 清冷绿调自带清透感,一戴秒变空灵猫眼，眼神像藏了片森林，纯欲又高级~'),
  ('弥生', '半年抛', '超大荧光水母', '人鱼系列', '棕', '14.5', '14.5', '', '', '', '', 'images/patterns/misho_halfyear_超大荧光水母_lens.jpg', 'images/patterns/misho_halfyear_超大荧光水母_eye.jpg', '深棕调如清透琥珀，上眼宛如把深海水母的荧光感揉进眸中，清透又自带柔光，大直径扩瞳效果绝绝子~'),
  ('弥生', '半年抛', '偷吻珊瑚', '人鱼系列', '黑粉', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_偷吻珊瑚_lens.jpg', 'images/patterns/misho_halfyear_偷吻珊瑚_eye.jpg', '这款花色漫画扩瞳娃感超浓，是网版砂糖粉底的同款，戴上像是在眼睛里打了腮红~'),
  ('弥生', '半年抛', '钓系美人', '人鱼系列', '紫色', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_halfyear_钓系美人_lens.jpg', 'images/patterns/misho_halfyear_钓系美人_eye.jpg', '宝子~这款花色是饱和度比较低的紫色，想要有些个性、但是又不突兀的花色
特点是紫色显白、融瞳~'),
  ('弥生', '半年抛', '绝情玫瑰烧', '人鱼系列', '红黑+拼色', '14.5', '13.96', '', '', '', '', 'images/patterns/misho_halfyear_绝情玫瑰烧_lens.jpg', 'images/patterns/misho_halfyear_绝情玫瑰烧_eye.jpg', '“绝情玫瑰烧” ，红棕调，眼神又 A 又魅惑'),
  ('弥生', '半年抛', '鲛人泪滴', '人鱼系列', '蓝棕拼色', '14.5', '14.13', '', '', '', '', '', 'images/patterns/misho_halfyear_鲛人泪滴_eye.jpg', '新品人鱼系列半年抛＃鲛人泪滴'),
  ('弥生', '半年抛', '深海之泪', '人鱼系列', '深蓝', '14.5', '14.12', '', '', '', '', 'images/patterns/misho_halfyear_深海之泪_lens.jpg', 'images/patterns/misho_halfyear_深海之泪_eye.jpg', '新品人鱼系列半年抛＃深海之泪'),
  ('弥生', '半年抛', '海豚恋人', '人鱼系列', '红棕', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_海豚恋人_lens.jpg', 'images/patterns/misho_halfyear_海豚恋人_eye.jpg', '新品人鱼系列半年抛＃海豚恋人'),
  ('弥生', '半年抛', '雾面珍珠', '人鱼系列', '黑灰', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_雾面珍珠_lens.jpg', 'images/patterns/misho_halfyear_雾面珍珠_eye.jpg', '新品人鱼系列半年抛＃雾面珍珠'),
  ('弥生', '半年抛', '贝母光晕', '人鱼系列', '棕色', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_halfyear_贝母光晕_lens.jpg', 'images/patterns/misho_halfyear_贝母光晕_eye.jpg', '很减龄可爱日常百搭款【贝母光晕】'),
  ('弥生', '半年抛', '落日熔金', '人鱼系列', '棕色', '14.5', '14.15', '', '', '', '', 'images/patterns/misho_halfyear_落日熔金_lens.jpg', 'images/patterns/misho_halfyear_落日熔金_eye.jpg', '新品人鱼系列半年抛＃落日熔金
「金棕瞳色+微闪细粉=狙击男神利器」'),
  ('弥生', '半年抛', '冰摇海葡萄', '人鱼系列', '紫色', '14.5', '13.9', '', '', '', '', 'images/patterns/misho_halfyear_冰摇海葡萄_lens.jpg', 'images/patterns/misho_halfyear_冰摇海葡萄_eye.jpg', '新品人鱼系列半年抛＃冰瑶海葡萄'),
  ('弥生', '半年抛', '黄油小熊', 'happy系列', '', '14.5', '14.15', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '快乐小狗', 'happy系列', '', '14.5', '14.15', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '松林小鹿', 'happy系列', '', '14.5', '13.97', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '美高舞会', 'happy系列', '', '14.5', '14.13', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '蜜糖戚风', 'happy系列', '', '14.2', '13.33', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '脆皮圣代', 'happy系列', '', '14.5', '13.9', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '纯白冬季', 'happy系列', '', '14.5', '13.9', '', '', '', '', '', '', ''),
  ('弥生', '半年抛', '记忆吐司', '花厨小熊系列', '红棕', '14.5', '13.8', '', '', '', '', 'images/patterns/misho_halfyear_记忆吐司_lens.jpg', 'images/patterns/misho_halfyear_记忆吐司_eye.jpg', ''),
  ('弥生', '半年抛', '曲奇饼派对', '花厨小熊系列', '棕色', '14.5', '14.05', '', '', '', '', 'images/patterns/misho_halfyear_曲奇饼派对_lens.jpg', 'images/patterns/misho_halfyear_曲奇饼派对_eye.jpg', '这款是暖棕焦糖棕调+金闪糖霜 曲奇饼般的甜酷鎏金瞳~'),
  ('弥生', '半年抛', '停止幻想', '花厨小熊系列', '黑灰', '14.5', '13.7', '', '', '', '', 'images/patterns/misho_halfyear_停止幻想_lens.jpg', 'images/patterns/misho_halfyear_停止幻想_eye.jpg', '【停止幻想】灰蓝花色+冰晶感纹理 很有银河感的赛博冰川瞳'),
  ('弥生', '半年抛', '黄油流心', '花厨小熊系列', '棕色', '14.5', '13.7', '', '', '', '', 'images/patterns/misho_halfyear_黄油流心_lens.jpg', 'images/patterns/misho_halfyear_黄油流心_eye.jpg', '【黄油流心】
黄油暖棕渐变+鎏金细闪 温柔又很特别的滤镜感~'),
  ('弥生', '半年抛', '奶油噗噗', '花厨小熊系列', '黑紫', '14.5', '14.2', '', '', '', '', 'images/patterns/misho_halfyear_奶油噗噗_lens.jpg', 'images/patterns/misho_halfyear_奶油噗噗_eye.jpg', '【奶油噗噗】柔黑调融瞳自然，眼神软萌又通透'),
  ('弥生', '半年抛', '灰熊奶霜', '花厨小熊系列', '黑色', '14.5', '14', '', '', '', '', 'images/patterns/misho_halfyear_灰熊奶霜_lens.jpg', 'images/patterns/misho_halfyear_灰熊奶霜_eye.jpg', '【灰熊奶霜】清冷灰调，眼神通透又高级'),
  ('弥生', '半年抛', '牛仔布偶', '花厨小熊系列', '黑蓝', '14.5', '14.1', '', '', '', '', 'images/patterns/misho_halfyear_牛仔布偶_lens.jpg', 'images/patterns/misho_halfyear_牛仔布偶_eye.jpg', '【牛仔布偶】深邃黑调，眼神慵懒又吸睛'),
  ('弥生', '半年抛', '偷心布朗尼', '花厨小熊系列', '棕色', '14.5', '14.12', '', '', '', '', 'images/patterns/misho_halfyear_偷心布朗尼_lens.jpg', 'images/patterns/misho_halfyear_偷心布朗尼_eye.jpg', '【偷心布朗尼】柔棕色调超绝，14.5mm 直径自然放大双眼，上眼宛如天生琉璃瞳持久水润，一键拿捏温柔心动感~'),
  ('弥生', '半年抛', '快乐小狗', '花厨小熊系列', '黑色', '14.5', '14.15', '', '', '', '', 'images/patterns/misho_halfyear_快乐小狗_lens.jpg', 'images/patterns/misho_halfyear_快乐小狗_eye.jpg', '【快乐小狗】纯黑色基底+渐变星空灰 扩瞳感的黑曜石狗狗瞳'),
  ('弥生', '半年抛', '黄油小熊', '花厨小熊系列', '棕色', '14.5', '14.15', '', '', '', '', 'images/patterns/misho_halfyear_黄油小熊_lens.jpg', 'images/patterns/misho_halfyear_黄油小熊_eye.jpg', '弥生美瞳新品 花厨小熊-【黄油小熊】，大直径打造清纯无辜感~'),
  ('极氧', '日抛', '糖霜日落', '晨露', '棕色系', '14.2mm', '13.47', '硅水凝胶', '100dk', '58%', '6片/盒', 'images/patterns/日抛_糖霜日落_lens.jpg', 'images/patterns/日抛_糖霜日落_eye.jpg', ''),
  ('极氧', '日抛', '暮色回响', '晨露', '黑灰色系', '14.2mm', '13.43', '硅水凝胶', '100dk', '58%', '6片/盒', '', 'images/patterns/日抛_暮色回响_eye.jpg', ''),
  ('极氧', '日抛', '梨漫花岛', '晨露', '棕色系', '14.2mm', '13.7', '硅水凝胶', '100dk', '58%', '6片/盒', 'images/patterns/日抛_梨漫花岛_lens.jpg', 'images/patterns/日抛_梨漫花岛_eye.jpg', ''),
  ('极氧', '日抛', '梨花杏雨', '晨露', '棕色系', '14.2mm', '13.6', '硅水凝胶', '100dk', '58%', '6片/盒', 'images/patterns/日抛_梨花杏雨_lens.jpg', 'images/patterns/日抛_梨花杏雨_eye.jpg', ''),
  ('极氧', '日抛', '樱落半夏', '晨露', '粉紫色系', '14.2mm', '13.4', '硅水凝胶', '100dk', '58%', '6片/盒', 'images/patterns/日抛_樱落半夏_lens.jpg', 'images/patterns/日抛_樱落半夏_eye.jpg', ''),
  ('极氧', '日抛', '琥珀柔光', '晨露', '棕色系', '14.2mm', '13.6', '硅水凝胶', '100dk', '58%', '6片/盒', 'images/patterns/日抛_琥珀柔光_lens.jpg', 'images/patterns/日抛_琥珀柔光_eye.jpg', ''),
  ('极氧', '日抛', '清欢水漾', '晨露', '绿色系', '14.2mm', '13.52', '硅水凝胶', '100dk', '58%', '6片/盒', '', 'images/patterns/日抛_清欢水漾_eye.jpg', ''),
  ('极氧', '日抛', '坠眼青花', '晨露', '灰色系', '14.2mm', '13.4', '硅水凝胶', '100dk', '58%', '6片/盒', '', 'images/patterns/日抛_坠眼青花_eye.jpg', ''),
  ('极氧', '日抛', '扶光云梦', '晨露', '蓝色系', '14.2mm', '13.15', '硅水凝胶', '100dk', '58%', '6片/盒', '', 'images/patterns/日抛_扶光云梦_eye.jpg', ''),
  ('极氧', '日抛', '风摇南枝', '森氧', '灰色系', '14.1mm', '13.8', '硅水凝胶', '150dk', '47%', '6片/盒', 'images/patterns/日抛_风摇南枝_lens.jpg', 'images/patterns/日抛_风摇南枝_eye.jpg', ''),
  ('极氧', '日抛', '春野鹿鸣', '森氧', '棕色系', '14.1mm', '13.7', '硅水凝胶', '150dk', '47%', '6片/盒', 'images/patterns/日抛_春野鹿鸣_lens.jpg', 'images/patterns/日抛_春野鹿鸣_eye.jpg', ''),
  ('极氧', '日抛', '梦蝶晚窗', '森氧', '棕色系', '14.1mm', '13.7', '硅水凝胶', '150dk', '47%', '6片/盒', 'images/patterns/日抛_梦蝶晚窗_lens.jpg', 'images/patterns/日抛_梦蝶晚窗_eye.jpg', ''),
  ('极氧', '日抛', '雪落松香', '森氧', '绿色系', '14.1mm', '13.7', '硅水凝胶', '150dk', '47%', '6片/盒', 'images/patterns/日抛_雪落松香_lens.jpg', 'images/patterns/日抛_雪落松香_eye.jpg', ''),
  ('极氧', '日抛', '晴空飞鸟', 'YOUHOO联名', '棕色系', '14.2mm', '13.5', '水凝胶', '', '40%-50%', '6片/盒', '', 'images/patterns/日抛_晴空飞鸟_eye.jpg', ''),
  ('极氧', '日抛', '溪山晚风', 'YOUHOO联名', '黑色系', '14.2mm', '12.8', '水凝胶', '', '40%-50%', '6片/盒', '', 'images/patterns/日抛_溪山晚风_eye.jpg', ''),
  ('极氧', '日抛', '莫奈花园', 'YOUHOO联名', '棕色系', '14.2mm', '13.55', '水凝胶', '', '50%', '6片/盒', '', 'images/patterns/日抛_莫奈花园_eye.jpg', ''),
  ('极氧', '日抛', '枫糖戚风', 'YOUHOO联名', '棕色系', '14.2mm', '14.0', '水凝胶', '', '40%-50%', '6片/盒', '', 'images/patterns/日抛_枫糖戚风_eye.jpg', ''),
  ('极氧', '日抛', '梨花慢慢', 'YOUHOO联名', '黑色系', '14.2mm', '13.8', '水凝胶', '', '50%', '6片/盒', '', 'images/patterns/日抛_梨花慢慢_eye.jpg', ''),
  ('极氧', '日抛', '邂逅洱海', 'YOUHOO联名', '蓝色系', '14.4mm', '13.6', '水凝胶', '', '50%', '6片/盒', '', 'images/patterns/日抛_邂逅洱海_eye.jpg', ''),
  ('极氧', '季抛', '极光金棕', '季抛系列', '棕色系', '14.1mm', '13.4', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_极光金棕_lens.jpg', 'images/patterns/季抛_极光金棕_eye.jpg', ''),
  ('极氧', '季抛', '极光黑灰', '季抛系列', '黑色系', '14.1mm', '13.5', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_极光黑灰_lens.jpg', 'images/patterns/季抛_极光黑灰_eye.jpg', ''),
  ('极氧', '季抛', '酒心巧克力', '季抛系列', '棕色系', '14.2mm', '13.6', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_酒心巧克力_lens.jpg', 'images/patterns/季抛_酒心巧克力_eye.jpg', ''),
  ('极氧', '季抛', '糖霜日落', '季抛系列', '棕色系', '14.2mm', '13.6', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_糖霜日落_lens.jpg', '', ''),
  ('极氧', '季抛', '月亮情诗', '季抛系列', '黑色系', '14.5mm', '14.2', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_月亮情诗_lens.jpg', '', ''),
  ('极氧', '季抛', '花漾甜梦', '季抛系列', '粉色系', '14.5mm', '14.1', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_花漾甜梦_lens.jpg', '', ''),
  ('极氧', '季抛', '松涧小鹿', '季抛系列', '棕色系', '14.5mm', '14.0', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_松涧小鹿_lens.jpg', '', ''),
  ('极氧', '季抛', '月光拿铁', '季抛系列', '棕色系', '14.5mm', '14.0', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_月光拿铁_lens.jpg', '', ''),
  ('极氧', '季抛', '椰影摇光', '季抛系列', '棕色系', '14.1mm', '13.1', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_椰影摇光_lens.jpg', '', ''),
  ('极氧', '季抛', '凌晨三点', '季抛系列', '蓝色系', '14.5mm', '14.1', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_凌晨三点_lens.jpg', '', ''),
  ('极氧', '季抛', '富士山雾', '季抛系列', '蓝色系', '14.1mm', '13.4', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_富士山雾_lens.jpg', 'images/patterns/季抛_富士山雾_eye.jpg', ''),
  ('极氧', '季抛', '榛果灰棕', '季抛系列', '棕色系', '14.5mm', '14.1', '水凝胶', '', '38%', '季抛', 'images/patterns/季抛_榛果灰棕_lens.jpg', 'images/patterns/季抛_榛果灰棕_eye.jpg', '');
