// 跟练课程库 - 模拟帕梅拉/HIIT/瑜伽等跟练体验
// 每个课程由一系列动作+时长组成，内置倒计时播放器

const courses = [
  {
    id: 'pamela_abs_10',
    name: '10分钟腹部轰炸',
    type: 'pamela',
    typeName: '帕梅拉',
    duration: 600,
    difficulty: '中级',
    target: '腹部核心',
    calories: 120,
    color: '#e74c3c',
    desc: '帕梅拉风格腹部训练，10分钟不间歇',
    biliBvid: 'BV1kA411q7cH',
    biliTitle: '帕梅拉10分钟腹部训练（新手友好）',
    exercises: [
      { name: '卷腹', time: 40, rest: 10 },
      { name: '俄罗斯转体', time: 40, rest: 10 },
      { name: '仰卧举腿', time: 40, rest: 10 },
      { name: '登山跑', time: 40, rest: 10 },
      { name: '卷腹', time: 40, rest: 10 },
      { name: '侧支撑', time: 30, rest: 10 },
      { name: '俄罗斯转体', time: 40, rest: 10 },
      { name: '仰卧举腿', time: 40, rest: 10 },
      { name: '登山跑', time: 40, rest: 10 },
      { name: '平板支撑', time: 40, rest: 10 },
      { name: '卷腹', time: 40, rest: 10 },
      { name: '仰卧举腿', time: 40, rest: 0 }
    ]
  },
  {
    id: 'pamela_legs_12',
    name: '12分钟蜜腿塑造',
    type: 'pamela',
    typeName: '帕梅拉',
    duration: 720,
    difficulty: '中级',
    target: '臀腿',
    calories: 150,
    color: '#e74c3c',
    desc: '帕梅拉风格下肢训练，塑造紧致腿型',
    biliBvid: 'BV1xd4y127Z8',
    biliTitle: '帕梅拉站立腿部普拉提',
    exercises: [
      { name: '深蹲', time: 45, rest: 15 },
      { name: '哑铃弓步蹲', time: 45, rest: 15 },
      { name: '臀桥', time: 45, rest: 15 },
      { name: '深蹲跳', time: 30, rest: 15 },
      { name: '保加利亚分腿蹲', time: 30, rest: 15 },
      { name: '臀桥', time: 45, rest: 15 },
      { name: '哑铃弓步蹲', time: 45, rest: 15 },
      { name: '深蹲', time: 45, rest: 15 },
      { name: '提踵', time: 40, rest: 15 },
      { name: '深蹲跳', time: 30, rest: 15 },
      { name: '哑铃硬拉', time: 45, rest: 15 },
      { name: '臀桥', time: 45, rest: 0 }
    ]
  },
  {
    id: 'hiit_full_15',
    name: '15分钟HIIT全身燃脂',
    type: 'hiit',
    typeName: 'HIIT',
    duration: 900,
    difficulty: '高级',
    target: '全身燃脂',
    calories: 200,
    color: '#ff6b35',
    desc: '高强度间歇训练，15分钟燃烧200大卡',
    biliBvid: 'BV1v5411a7c1',
    biliTitle: '帕梅拉卡路里杀手HIIT',
    exercises: [
      { name: '开合跳', time: 40, rest: 20 },
      { name: '深蹲跳', time: 40, rest: 20 },
      { name: '俯卧撑', time: 40, rest: 20 },
      { name: '波比跳', time: 40, rest: 20 },
      { name: '高抬腿', time: 40, rest: 20 },
      { name: '登山跑', time: 40, rest: 20 },
      { name: '开合跳', time: 40, rest: 20 },
      { name: '深蹲跳', time: 40, rest: 20 },
      { name: '波比跳', time: 40, rest: 20 },
      { name: '俯卧撑', time: 40, rest: 20 },
      { name: '高抬腿', time: 40, rest: 20 },
      { name: '登山跑', time: 40, rest: 20 },
      { name: '开合跳', time: 40, rest: 20 },
      { name: '波比跳', time: 40, rest: 20 },
      { name: '深蹲跳', time: 40, rest: 0 }
    ]
  },
  {
    id: 'hiit_quick_7',
    name: '7分钟快速燃脂',
    type: 'hiit',
    typeName: 'HIIT',
    duration: 420,
    difficulty: '初级',
    target: '全身',
    calories: 80,
    color: '#f39c12',
    desc: '没时间？7分钟快速出汗',
    biliBvid: 'BV1br4y1A7Zr',
    biliTitle: '帕梅拉最佳HIIT训练',
    exercises: [
      { name: '开合跳', time: 45, rest: 15 },
      { name: '深蹲', time: 45, rest: 15 },
      { name: '俯卧撑', time: 45, rest: 15 },
      { name: '高抬腿', time: 45, rest: 15 },
      { name: '登山跑', time: 45, rest: 15 },
      { name: '波比跳', time: 45, rest: 15 },
      { name: '平板支撑', time: 45, rest: 0 }
    ]
  },
  {
    id: 'core_beginner_8',
    name: '8分钟核心入门',
    type: 'core',
    typeName: '核心',
    duration: 480,
    difficulty: '初级',
    target: '核心力量',
    calories: 60,
    color: '#9b59b6',
    desc: '核心训练入门，适合新手',
    biliBvid: 'BV1ba411874w',
    biliTitle: '帕梅拉慢速腹肌训练',
    exercises: [
      { name: '平板支撑', time: 30, rest: 15 },
      { name: '卷腹', time: 30, rest: 15 },
      { name: '仰卧举腿', time: 30, rest: 15 },
      { name: '俄罗斯转体', time: 30, rest: 15 },
      { name: '超人式', time: 30, rest: 15 },
      { name: '侧支撑', time: 20, rest: 10 },
      { name: '登山跑', time: 30, rest: 15 },
      { name: '平板支撑', time: 30, rest: 15 },
      { name: '卷腹', time: 30, rest: 15 },
      { name: '仰卧举腿', time: 30, rest: 0 }
    ]
  },
  {
    id: 'core_advanced_10',
    name: '10分钟核心进阶',
    type: 'core',
    typeName: '核心',
    duration: 600,
    difficulty: '高级',
    target: '腹部核心',
    calories: 100,
    color: '#9b59b6',
    desc: '高难度核心挑战，练出马甲线',
    biliBvid: 'BV1DV411H77T',
    biliTitle: '帕梅拉杀手腹肌训练',
    exercises: [
      { name: '平板支撑', time: 45, rest: 15 },
      { name: '登山跑', time: 40, rest: 10 },
      { name: '卷腹', time: 40, rest: 10 },
      { name: '俄罗斯转体', time: 40, rest: 10 },
      { name: '仰卧举腿', time: 40, rest: 10 },
      { name: '波比跳', time: 30, rest: 15 },
      { name: '侧支撑', time: 30, rest: 10 },
      { name: '登山跑', time: 40, rest: 10 },
      { name: '卷腹', time: 40, rest: 10 },
      { name: '仰卧举腿', time: 40, rest: 10 },
      { name: '平板支撑', time: 45, rest: 0 }
    ]
  },
  {
    id: 'stretch_10',
    name: '10分钟全身拉伸',
    type: 'stretch',
    typeName: '拉伸',
    duration: 600,
    difficulty: '初级',
    target: '柔韧性',
    calories: 40,
    color: '#2ecc71',
    desc: '训练后或日常放松拉伸',
    biliBvid: 'BV1vV411C76c',
    biliTitle: '帕梅拉5分钟每日拉伸',
    exercises: [
      { name: '平板支撑', time: 30, rest: 10 },
      { name: '超人式', time: 30, rest: 10 },
      { name: '臀桥', time: 30, rest: 10 },
      { name: '深蹲', time: 30, rest: 10 },
      { name: '卷腹', time: 30, rest: 10 },
      { name: '仰卧举腿', time: 30, rest: 10 },
      { name: '侧支撑', time: 20, rest: 10 },
      { name: '超人式', time: 30, rest: 10 },
      { name: '臀桥', time: 30, rest: 10 },
      { name: '平板支撑', time: 30, rest: 10 },
      { name: '深蹲', time: 30, rest: 10 },
      { name: '卷腹', time: 30, rest: 0 }
    ]
  },
  {
    id: 'pamela_arm_8',
    name: '8分钟手臂线条',
    type: 'pamela',
    typeName: '帕梅拉',
    duration: 480,
    difficulty: '初级',
    target: '手臂肩部',
    calories: 70,
    color: '#e74c3c',
    desc: '帕梅拉风格手臂训练，告别拜拜肉',
    biliBvid: 'BV18t4y1w7Ef',
    biliTitle: '帕梅拉12分钟优雅手臂',
    exercises: [
      { name: '侧平举', time: 40, rest: 10 },
      { name: '哑铃弯举', time: 40, rest: 10 },
      { name: '哑铃臂屈伸', time: 40, rest: 10 },
      { name: '前平举', time: 40, rest: 10 },
      { name: '锤式弯举', time: 40, rest: 10 },
      { name: '颈后臂屈伸', time: 40, rest: 10 },
      { name: '侧平举', time: 40, rest: 10 },
      { name: '哑铃弯举', time: 40, rest: 10 },
      { name: '哑铃臂屈伸', time: 40, rest: 10 },
      { name: '俯身飞鸟', time: 40, rest: 0 }
    ]
  },
  {
    id: 'cardio_dance_20',
    name: '20分钟有氧燃脂',
    type: 'cardio',
    typeName: '有氧',
    duration: 1200,
    difficulty: '中级',
    target: '全身燃脂',
    calories: 250,
    color: '#3498db',
    desc: '持续有氧训练，暴汗燃脂',
    biliBvid: 'BV1o64y1T7KV',
    biliTitle: '帕梅拉有氧舞蹈',
    exercises: [
      { name: '开合跳', time: 60, rest: 15 },
      { name: '高抬腿', time: 45, rest: 15 },
      { name: '深蹲跳', time: 45, rest: 15 },
      { name: '登山跑', time: 45, rest: 15 },
      { name: '波比跳', time: 30, rest: 15 },
      { name: '开合跳', time: 60, rest: 15 },
      { name: '高抬腿', time: 45, rest: 15 },
      { name: '深蹲跳', time: 45, rest: 15 },
      { name: '登山跑', time: 45, rest: 15 },
      { name: '波比跳', time: 30, rest: 15 },
      { name: '开合跳', time: 60, rest: 15 },
      { name: '高抬腿', time: 45, rest: 15 },
      { name: '深蹲跳', time: 45, rest: 15 },
      { name: '登山跑', time: 45, rest: 15 },
      { name: '波比跳', time: 30, rest: 15 },
      { name: '开合跳', time: 60, rest: 0 }
    ]
  },
  {
    id: 'pamela_booty_10',
    name: '10分钟翘臀训练',
    type: 'pamela',
    typeName: '帕梅拉',
    duration: 600,
    difficulty: '中级',
    target: '臀部',
    calories: 100,
    color: '#e74c3c',
    desc: '帕梅拉风格翘臀训练，蜜桃臀练起来',
    biliBvid: 'BV1Ck4y127oC',
    biliTitle: '帕梅拉臀部训练',
    exercises: [
      { name: '臀桥', time: 45, rest: 15 },
      { name: '哑铃弓步蹲', time: 40, rest: 15 },
      { name: '深蹲', time: 45, rest: 15 },
      { name: '保加利亚分腿蹲', time: 30, rest: 15 },
      { name: '臀桥', time: 45, rest: 15 },
      { name: '哑铃硬拉', time: 45, rest: 15 },
      { name: '深蹲跳', time: 30, rest: 15 },
      { name: '哑铃弓步蹲', time: 40, rest: 15 },
      { name: '臀桥', time: 45, rest: 15 },
      { name: '保加利亚分腿蹲', time: 30, rest: 0 }
    ]
  }
];

const courseTypes = [
  { id: 'all', name: '全部', icon: '🔥' },
  { id: 'pamela', name: '帕梅拉', icon: '💃' },
  { id: 'hiit', name: 'HIIT', icon: '⚡' },
  { id: 'core', name: '核心', icon: '🎯' },
  { id: 'cardio', name: '有氧', icon: '🏃' },
  { id: 'stretch', name: '拉伸', icon: '🧘' }
];

module.exports = { courses, courseTypes };
